const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, Header, Footer, AlignmentType, LevelFormat, HeadingLevel, BorderStyle, PageNumber, PageBreak } = require("docx");
const c = "2D4A2D";
function h1(t){return new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:360,after:200},children:[new TextRun({text:t,bold:true,font:"Georgia",size:32,color:c})]});}
function h2(t){return new Paragraph({heading:HeadingLevel.HEADING_2,spacing:{before:280,after:160},children:[new TextRun({text:t,bold:true,font:"Georgia",size:26,color:c})]});}
function p(t,o={}){return new Paragraph({spacing:{after:120},children:[new TextRun({text:t,font:"Arial",size:21,color:"333333",...o})]});}
function bp(l,t){return new Paragraph({spacing:{after:120},children:[new TextRun({text:l,font:"Arial",size:21,bold:true,color:"333333"}),new TextRun({text:t,font:"Arial",size:21,color:"333333"})]});}
const refs=[];for(let i=0;i<15;i++){refs.push({reference:"b"+i,levels:[{level:0,format:LevelFormat.BULLET,text:"\u2022",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]});refs.push({reference:"n"+i,levels:[{level:0,format:LevelFormat.DECIMAL,text:"%1.",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]});}
let bi=0,ni=0;
function bul(t){return new Paragraph({numbering:{reference:"b"+bi,level:0},spacing:{after:80},children:[new TextRun({text:t,font:"Arial",size:21,color:"333333"})]});}
function bbul(l,t){return new Paragraph({numbering:{reference:"b"+bi,level:0},spacing:{after:80},children:[new TextRun({text:l,font:"Arial",size:21,bold:true,color:"333333"}),new TextRun({text:t,font:"Arial",size:21,color:"333333"})]});}
function bnum(l,t){return new Paragraph({numbering:{reference:"n"+ni,level:0},spacing:{after:80},children:[new TextRun({text:l,font:"Arial",size:21,bold:true,color:"333333"}),new TextRun({text:t,font:"Arial",size:21,color:"333333"})]});}
function nb(){bi++;}function nn(){ni++;}
function pb(){return new Paragraph({children:[new PageBreak()]});}

const doc = new Document({
  numbering:{config:refs},
  sections:[
    {properties:{page:{size:{width:12240,height:15840},margin:{top:2880,right:1440,bottom:1440,left:1440}}},children:[
      p(""),p(""),
      new Paragraph({spacing:{after:200},children:[new TextRun({text:"VALUATION REALIZED",font:"Georgia",size:48,bold:true,color:c})]}),
      new Paragraph({spacing:{after:100},children:[new TextRun({text:"Productized M&A Exit Prep for SMEs",font:"Georgia",size:28,color:"666666",italics:true})]}),
      new Paragraph({spacing:{after:400},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:c,space:1}},children:[]}),
      p("Design Document",{size:24,color:"666666"}),
      p("Generated by /office-hours on 2026-03-21",{size:20,color:"999999"}),
      p("Status: APPROVED  |  Mode: Startup  |  2-Week Sprint",{size:20,color:"999999"}),
      p("Author: Vaiga Rimsaite, CFA",{size:20,color:"999999"}),
    ]},
    {properties:{page:{size:{width:12240,height:15840},margin:{top:1440,right:1440,bottom:1440,left:1440}}},
    headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun({text:"Valuation Realized \u2014 Design Document",font:"Arial",size:16,color:"999999",italics:true})]})]})},
    footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:"Page ",font:"Arial",size:16,color:"999999"}),new TextRun({children:[PageNumber.CURRENT],font:"Arial",size:16,color:"999999"})]})]})},
    children:[
      h1("Problem Statement"),
      p("SME founders/owners ($2-50M revenue) planning an exit in 6-18 months face a devastating information asymmetry: buyers and investors run hundreds of deals and systematically apply valuation haircuts during due diligence. Founders typically make 1-2 exits in their entire career and don\u2019t know what\u2019s coming. The result: a preventable 30% valuation haircut that the founder discovers too late to fix."),
      p("Big Four firms (EY, Deloitte, PwC, KPMG) offer sell-side preparation, but at $90K+ minimum \u2014 prohibitive for an SME. This leaves a massive gap: Big Four quality exit preparation at an accessible price point."),
      h1("Demand Evidence"),
      bp("One real sale (accidental): ","At a networking event, a founder asked for help valuing his company. EY quoted $90K minimum. Vaiga offered a personal $2K mini-valuation \u2014 and closed the deal on the spot. The EY credential alone was enough to close."),
      bp("Key signal: ","The founder sought her out. She didn\u2019t pitch. Demand pulled her \u2014 she didn\u2019t push the product."),
      bp("Price arbitrage: ","45x gap between Big Four ($90K) and independent Big Four alumna ($2K). Even at $8-15K, the value proposition is 6-10x cheaper with the same caliber expertise."),
      bp("Structural asymmetry: ","Investors make 100s of deals; founders make 1-2. Every SME exit repeats the same pattern \u2014 unprepared seller, sophisticated buyer, preventable value destruction."),
      h1("Status Quo"),
      bp("Gap: ","8 years on the buyer/advisor side at EY-Parthenon. Deep DD knowledge. But the SME seller\u2019s journey hasn\u2019t been mapped yet."),
      p("Likely status quo (to validate):",{bold:true}),
      bul("Founder asks accountant for valuation (back-of-napkin industry multiples)"),
      bul("Founder contacts broker (\u201Chandle everything\u201D \u2014 incentivized to close fast)"),
      bul("Founder enters DD unprepared; buyer reduces price"),
      bul("Or: founder doesn\u2019t prepare because they don\u2019t know they should"),nb(),
      bp("Assignment: ","Interview 5-10 founders who sold. Map the journey."),
      h1("Target User & Narrowest Wedge"),
      bp("Target: ","Founder/owner/CEO/CFO of SME ($2-50M revenue), planning exit in 6-18 months."),
      p("Sale Readiness Audit ($2-3K)",{bold:true,size:24}),
      bul("Diagnostic: 2-3 sessions, 1-2 weeks, identifying DD valuation risks"),
      bul("Deliverable: top 5-10 risks with impact (% of EV), severity, remediation steps"),
      bul("Price: $2-3K (test with first 3 clients)"),
      bul("Upsell: Exit Readiness Program ($8-15K) \u2014 2-4 month implementation"),nb(),
      bp("Boundary: ","Audit = diagnostic. Program = implementation. Clear separation."),
      pb(),
      h1("Phase 0: EY Employment Gate"),
      p("BLOCKER \u2014 Resolve Before Anything Else",{bold:true,color:"CC0000"}),
      p("If EY prohibits moonlighting or has a non-compete:"),
      bbul("If allowed: ","Proceed. Organic pipeline while employed."),
      bbul("If NOT allowed: ","Content-only mode. /exitreadiness becomes a waitlist."),nb(),
      bp("Action: ","Review contract this week. Consult UAE employment lawyer if unclear (~$300-500)."),
      h1("Competitive Landscape"),
      bul("Independent M&A advisors and fractional CFOs"),
      bul("Exit planning consultants (Exit Planning Institute, Value Scout)"),
      bul("Business brokers offering preparation"),
      bul("Online courses and DIY resources"),nb(),
      bp("Edge: ","EY-Parthenon + CFA + $70bn+ deal experience. Few independents match this."),
      h1("Premises"),
      bnum("Prevent the 30% haircut. ","Quantifiable, specific value prop."),
      bnum("EY credential IS the product. ","8 years, CFA, $70bn+ deals."),
      bnum("Awareness > competition. ","Real competitor is \u201Cdoing nothing.\u201D"),
      bnum("Pricing: ","$2-3K audit, $8-15K prep. 6-10x cheaper than Big Four."),
      bnum("Build pipeline before leaving EY. ","Prove model first."),nn(),
      pb(),
      h1("2-Week Intensive Sprint (March 21 \u2013 April 4)"),
      p("Commitment: 12 hours/day. All workstreams run simultaneously.",{bold:true,color:"CC0000"}),

      h2("Week 1: Build Everything in Parallel (March 21-28)"),
      p("Morning block (6 hrs) \u2014 Content + Outreach:",{bold:true}),
      bul("LinkedIn content DAILY (5-7 posts this week, not 3x/week)"),
      bul("DM 10+ founders per day who match target profile"),
      bul("Offer free 30-min Exit Readiness Check to first 5 responders"),
      bul("Talk to 3+ founders who have sold \u2014 mine their language for VSL"),
      bul("Create Exit Readiness Scorecard lead magnet"),nb(),
      p("Afternoon block (6 hrs) \u2014 VSL + Funnel:",{bold:true}),
      bul("Day 1-2: Write VSL script (Problem \u2192 Agitate \u2192 Solution \u2192 Offer \u2192 Credibility)"),
      bul("Day 2-3: Record VSL v1 on camera. Get Quentin\u2019s feedback."),
      bul("Day 3-4: Edit VSL. Keep under 10 minutes."),
      bul("Day 4-5: Build /exitreadiness landing page (VSL + email gate + Calendly)"),
      bul("Day 5-7: Install Meta Pixel + GA4. Test full funnel end-to-end."),nb(),
      p("Day 1 parallel: Check EY contract (non-compete, moonlighting, IP). Call lawyer if unclear.",{bold:true}),

      h2("Week 2: Launch + First Clients (March 29 \u2013 April 4)"),
      p("Morning (6 hrs) \u2014 Outreach at Scale:",{bold:true}),
      bul("Continue daily LinkedIn posts (10-14 total across both weeks)"),
      bul("Increase DMs to 15-20 founders/day"),
      bul("Book and complete first Exit Readiness Checks"),
      bul("Convert 1-2 into paid audits ($2-3K)"),
      bul("Collect testimonials from every conversation"),nb(),
      p("Afternoon (6 hrs) \u2014 Ads + Optimization:",{bold:true}),
      bul("Create 3-5 ad creatives for Meta + LinkedIn"),
      bul("Launch first campaign: $50-100/day"),
      bul("Monitor CTR, CPL, landing page conversion. Kill losers, scale winners."),
      bul("Iterate VSL if real conversations reveal better language"),nb(),

      h2("Phase 2: Optimize (Weeks 3-4)"),
      bul("LinkedIn 3x/week (sustainable pace)"),
      bul("Optimize ads from first 2 weeks of data"),
      bul("Close first 2-3 paid audits"),
      bul("Refine audit deliverable template"),
      bul("Collect video testimonials"),nb(),

      h2("Phase 3: Scale (Month 2+)"),
      bul("Templatize deliverables from first 5+ clients"),
      bul("Scale ad spend once CAC < 30% of deal size"),
      bul("Build referral engine"),
      bul("Consider group programs / courses"),nb(),

      pb(),
      h1("Success Criteria"),
      p("End of Week 1 (March 28):",{bold:true}),
      bnum("","EY contract reviewed"),
      bnum("","5-7 LinkedIn posts published"),
      bnum("","50+ founders DMed"),
      bnum("","VSL v1 recorded and edited"),
      bnum("","/exitreadiness live with VSL + email gate + Calendly"),nn(),
      p("End of Week 2 (April 4):",{bold:true}),
      bnum("","10-14 total LinkedIn posts"),
      bnum("","100+ founders DMed"),
      bnum("","First ad campaign running ($50-100/day)"),
      bnum("","3-5 ad creatives tested"),
      bnum("","First 1-2 Exit Readiness Checks completed"),
      bnum("","At least 1 paid audit booked ($2-3K)"),nn(),
      p("End of Month 1 (April 21):",{bold:true}),
      bnum("","Landing page conversion > 5%"),
      bnum("","2-3 paid clients closed"),
      bnum("","Close rate on calls > 20%"),
      bnum("","At least 1 testimonial collected"),nn(),

      h1("Dependencies"),
      bbul("DAY 1: ","EY contract review (non-compete/moonlighting)"),
      bbul("DAY 1: ","Regulatory check for M&A licensing"),
      bul("Week 1: VSL recording setup (camera, lighting, space \u2014 or Quentin\u2019s studio)"),
      bul("Week 1: /exitreadiness page build"),
      bul("Week 1: Meta Pixel + GA4 installation"),
      bul("Week 1: Calendly integration"),
      bul("Week 1: Quentin\u2019s funnel benchmarks"),
      bul("Week 2: Ad creatives (3-5 variants)"),
      bul("Week 2: Meta Business Manager + LinkedIn Campaign Manager setup"),nb(),

      h1("Open Questions"),
      bnum("","Non-compete situation at EY?"),
      bnum("","Geographic focus: MENA, Europe, or global?"),
      bnum("","Industry specialization or generalist?"),nn(),

      pb(),
      h1("Day 1 Checklist (Today)"),
      bnum("Check EY contract. ","Non-compete, moonlighting, IP. Book lawyer if unclear."),
      bnum("Publish first LinkedIn post. ","\u201CIn 8 years at EY, buyers slash valuations 30% during DD. 3 most common reasons \u2014 all preventable.\u201D CTA: DM me EXIT."),
      bnum("DM 10 founders ","who match the profile. Offer free Exit Readiness Check."),
      bnum("Write VSL script. ","Problem \u2192 Agitate \u2192 Solution \u2192 Offer \u2192 Credibility. Your 8 years of buyer-side stories ARE the content."),nn(),
      p(""),
      p("The VSL doesn\u2019t need to be perfect. It needs to exist. You can re-record in Week 2 with better language. A live imperfect funnel beats a perfect funnel that doesn\u2019t exist.",{italics:true,color:"666666"}),
      pb(),
      h1("What I Noticed About How You Think"),
      p("You didn\u2019t pitch at the networking event. You listened and offered a solution. That\u2019s consultative selling \u2014 and why the $8K+ model will work."),p(""),
      p("You framed the opportunity as \u201Cinvestors make 100s of deals, founders make 1-2.\u201D That\u2019s a mission statement. The asymmetry framing makes the problem feel unfair and your service feel like justice. Use that exact language in your VSL."),p(""),
      p("You sold a valuation you\u2019d never done on EY credibility alone. The market is buying you, not a methodology. This is why the VSL must feature you on camera. You are the product."),p(""),
      p("You chose \u201CSale Readiness Audit\u201D as the wedge over full-service. Good instinct \u2014 a diagnostic is lower risk for the buyer and naturally upsells. Most first-time entrepreneurs try to sell everything on day one."),
    ]}
  ]
});

Packer.toBuffer(doc).then(buffer => {
  const path = require("path");
  const out = path.join(process.cwd(), "Valuation Realized", "Valuation-Realized-Design-Doc.docx");
  fs.writeFileSync(out, buffer);
  console.log("SUCCESS: " + out + " (" + (buffer.length/1024).toFixed(0) + " KB)");
}).catch(e => console.error("ERROR:", e.message));
